# Generated by Django 5.0.2 on 2024-02-29 09:25

import liberty_market.uitls
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='templates/liberty_market/assets/images/discover-01.jpg', upload_to=liberty_market.uitls.item_photos),
        ),
    ]
