# Generated by Django 5.0.2 on 2024-02-29 10:45

import django.db.models.deletion
import liberty_market.uitls
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty_market', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=liberty_market.uitls.item_photos),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='liberty_market.item')),
            ],
        ),
    ]
