# Generated by Django 5.0.2 on 2024-02-29 12:54

import liberty_market.uitls
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty_market', '0004_itemlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(upload_to=liberty_market.uitls.item_photos),
        ),
    ]
